/** @format */
'use client';
import React, {useState} from 'react';
import Sidebar from '@/components/sidebar/Sidebar';
import './globals.css';
import {Roboto, Inter} from 'next/font/google';
import Header from '@/components/header/Header';

const inter = Inter({subsets: ['latin']});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({children}) {
   const [openSidebar, setOpenSidebar] = useState(false);
   return (
      <html lang='en'>
         <body className='containers'>
            <Sidebar openSidebar={openSidebar} />
            <div className='contentWrap'>
               <Header setOpenSidebar={setOpenSidebar} openSidebar={openSidebar} />
               {children}
            </div>
         </body>
      </html>
   );
}
